version: 2.1
jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install -g saucectl
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  # Cypress Example
  test-cypress:
    working_directory: ~/app
    docker:
      - image: saucelabs/stt-cypress-mocha-node:latest
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Cypress Tests
          command: |
            git clone git@github.com:saucelabs/sauce-cypress-runner.git
            cd sauce-cypress-runner/tests/kitchen-sink-tests/
            saucectl run
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - test-cypress:
          requires:
            - setup